jobs:
  checkstyle:
    name: Checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      uses: reviewdog/action-setup@v1
      with:
        reviewdog_version: latest
    - continue-on-error: true
      name: download checkstyle
      run: curl -o checkstyle.jar -L https://github.com/checkstyle/checkstyle/releases/download/checkstyle-9.3/checkstyle-9.3-all.jar
    - continue-on-error: true
      env:
        REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      name: checkstyle
      run: java -jar checkstyle.jar -c config/checkstyle/checkstyle.xml -f xml . |
        reviewdog -f=checkstyle -name="Checkstyle Report" -reporter="github-check"
        -fail-on-error=true -level="error" -filter-mode=nofilter
  mysql-integration-test:
    runs-on: self-hosted
    services:
      mysql:
        env:
          MYSQL_DATABASE: databasir
          MYSQL_ROOT_PASSWORD: '123456'
        image: mysql:5.7
        ports:
        - 3306:3306
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        cache: gradle
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      name: Gradle Permission Grant
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Gradle Test
      run: ./gradlew api:check core:check
    - continue-on-error: true
      if: always()
      name: Publish Test Report
      uses: mikepenz/action-junit-report@v3
      with:
        report_paths: '**/build/test-results/test/TEST-*.xml'
name: check
on:
  repository_dispatch:
    types: trigger-ga___auto-check.yml
