jobs:
  release:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        server-id: github
        settings-path: ${{ github.workspace }}
    - continue-on-error: true
      name: Gradle Permission Grant
      run: chmod +x ./gradlew
    - continue-on-error: true
      name: Gradle Build
      run: ./gradlew api:build -x checkstyleMain -x checkstyleTest
    - continue-on-error: true
      name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
    - continue-on-error: true
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - continue-on-error: true
      name: Docker Image Release
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./local.Dockerfile
        platforms: linux/amd64,linux/arm64
        push: false
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/databasir:latest
name: docker latest
on:
  repository_dispatch:
    types: trigger-ga___auto-docker-latest.yml
